CREATE TABLE USERS (
  ID INT NOT NULL,
  USERNAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE VARCHAR(45) NOT NULL,
  LASTPASSWORDRESETDATE VARCHAR(45) NULL,
  ENABLED BIT(1) NULL DEFAULT 1,
  PRIMARY KEY (ID),
  UNIQUE INDEX EMAIL_UNIQUE (EMAIL ASC),
  UNIQUE INDEX USERNAME_UNIQUE (USERNAME ASC));
